apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort #외부에서 우분투 서버 IP로 바로 접속할 수 있게 해주는 설정
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 #ip주소:30080으로 접속
